global:
  scrape_interval: 2s

scrape_configs:
  # - job_name: 'vector-app'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['127.0.0.1:2112']
  - job_name: weaviate
    scrape_interval: 2s
    static_configs:
      - targets:
        - weaviate:2112
